<br>
<hr style="border: solid 1px red; margin-bottom: -1% ">
# Session 2: NumPy  
<hr style="border: solid 1px red; margin-top: 1.5% ">




<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Introducing NumPy
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>

* NumPy supports:

  * Multidimensional arrays (`ndarray`)
  * Matrices and linear algebra operations
  * Random number generation
  * Fourier transforms
  * Polynomials
  
* NumPy provides fast precompiled functions for numerical routines


* https://www.numpy.org/

<br>
<br>

<hr style="border: solid 1px red; margin-bottom: 2% ">
## NumPy Arrays
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>

* Core (or Standard) Python Library provides lists and 1d arrays (array.array)

  * Lists are general containers for objects
  * Arrays are 1d containers for objects of the same type
  * Limited functionality
  * Some memory and performance overhead associated with these structures


* NumPy provides multidimensional arrays (numpy.ndarray)
  * Can store many elements of the same data type in multiple dimensions
  * cf. Fortran/C/C++ arrays
  * More functionality than Core Python e.g. many conveninent methods for array manipulation
  * Efficient storage and execution

See, e.g.,
* https://docs.scipy.org/doc/
<br>
<br>

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Creating 1d arrays
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>
Import `numpy` as alias "np"

In [1]:
import numpy as np

Many ways to create 1d array e.g. from a list

In [3]:
original = [-1, 0, 1]
print(original)
a = np.array(original)
print (a)
print (type(a))

[-1, 0, 1]
[-1  0  1]
<class 'numpy.ndarray'>


In [8]:
b = np.linspace(-10, 10, 5)
print (b)
print (type(b))

[-10.  -5.   0.   5.  10.]
<class 'numpy.ndarray'>


Or from other arrays ("copy constructor")

In [9]:
c = b
print (c)

#There is a distinction betwen deep copies and shallow copies of arrays

[-10.  -5.   0.   5.  10.]


All Numpy arrays are of type '`ndarray`'

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Creating 1d arrays (cont.)
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

Can create arrays using `numpy` functions, e.g.

Can you guess what the following functions do?

In [10]:
a = np.linspace(-10, 10, 5)

In [12]:
print (a)
print ("Dimensions: ", a.ndim)
print ("Shape: ", a.shape)
print ("Size: ", a.size)
print ("Data type: ", a.dtype)

[-10.  -5.   0.   5.  10.]
Dimensions:  1
Shape:  (5,)
Size:  5
Data type:  float64


In [13]:
#Create array and define data type
a = np.array( [1,2,3], np.int16)

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Array attributes
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>
As part of the array structure, Numpy keeps track of metadata for the array as "attributes"

Can specify data type at creation

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Multi-dimensional arrays
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

Many different ways to create N-dimensional arrays. A two-dimensional array or matrix can be created from, e.g., list of lists

In [14]:
mat = np.array ([[1,2,3], [4,5,6]])

Question: 
Work out the dimensions, size and shape of 'mat'

In [17]:
print ("Dimensions: ", mat.ndim)
print ("Size: ", mat.size)
print ("Shape: ", mat.shape)

Dimensions:  2
Size:  6
Shape:  (2, 3)


In [19]:
#Concatenating arrays
d = np.r_[np.array( [1,2,3]), 0 , 0 , [4,5,6]]
print (d)
print (d.shape)

d = np.c_[np.array( [1,2,3]), [4,5,6] ]
print (d)
print (d.shape)

[1 2 3 0 0 4 5 6]
(8,)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Accessing arrays
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>

Basic indexing and slicing can be used to access array elements, as we know from lists

In [22]:
a = np.arange(8)
print(a)

print (a[0:7:2])
print (a[0::2])

[0 1 2 3 4 5 6 7]
[0 2 4 6]
[0 2 4 6]


Negative indices are valid!

In [23]:
print (a[2:-3:2])
#Last element
print (a[-1])

[2 4]
7


Can you guess the output of the following cell?

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Accessing arrays (cont.)
<hr style="border: solid 1px red margin-bottom: -1%; ">
<br>
For multi-dimensional arrays, can use a tuples or index notation.

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Array copies
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>
Simple assignment creates references or 'shallow' copies of arrays

In [24]:
a = np.arange(8)
b = a
print (a)
print (b)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [25]:
a[3] = 0
print(a)
print(b)

[0 1 2 0 4 5 6 7]
[0 1 2 0 4 5 6 7]


Use `copy()` to create a true or 'deep' copy

In [28]:
e = np.arange(8)
f = np.copy(e)
print(e)
print (f)
e[4]= 1
print (e)
print (f)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[0 1 2 3 1 5 6 7]
[0 1 2 3 4 5 6 7]


<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Slices and views
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>
A "view" is an array that refers to another array’s data (like references). You can create a view on an array by selecting a slice of an array. No data is copied when a view is created. 

Question: Change all the elements with values 7,8,10,11 in matrix `m` below (i.e. bottom right corner elements) to 1000 using a slice

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Reshaping arrays
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

Can modify the shape of an array and/or change its size.

In [29]:
g = np.arange(6)
print (g)

[0 1 2 3 4 5]


In [34]:
h = g.reshape([2,3])
print (h)
print ("Shape:", h.shape )

[[0 1 2]
 [3 4 5]]
Shape: (2, 3)


Can check if arrays share the same data (i.e. not a copy) using `base`

Question: What does the `reshape()` method do?

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Manipulating arrays
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

There are many methods for manipulating arrays (reshaping, joining, splitthing, inserting, ...). Check the documentation.

E.g.,
```python
concatenate((a1,a2),axis=0)
split(a, indices_or_sections, axis=0)
flatten
ravel(a)
stack(arrays[, axis])
tile(a, reps)
repeat(a, repeats[, axis])
unique(ar[, return_index, return_inverse, ...])
trim_zeros(filt[, trim])
fill(scalar)
xv, yv = meshgrid(x,y)
```

Activity: See what arrays you can create from some of the functions listed above.

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Fancy indexing
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>
Advanced or fancy indexing lets you do more than simple indexing.


Fancy indexing returns a copy (not a view like slicing)

Use `base` to check whether `q` is a copy. Do the same for a simple indexed slice of `p` (e.g. `p[1:2,3:4]`)

Can use logical expressions and boolean 'masks' to find indices of elements of interest e.g.

Activity: What does the following code do?

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## 'Vectorisation'
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

'Vectorisation' allows element-wise operations (no loop!). What output do the following cells give?

Careful - type of data elements matters

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Random number generation
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>
Numpy provides utilities for random number generation

Activity: 

Explore other ways of generating random numbers. 
What other distributions can you sample? 

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## File operations
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>
Numpy provides an easy way to save data to text file

More flexibility with `genfromtext()`  (query `?np.genfromtext`)

Question: What do `numpy.save()` and `numpy.load()` do ?

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Example : Polynomials
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

Can represent polynomials with the numpy class `Polynomial` from `numpy.polynomial.Polynomial`


* `Polynomial([a, b, c, d, e])` creates a polynomial  $p(x) = a\,+\,b\,x \,+\,c\,x^2\,+\,d\,x^3\,+\,e\,x^4$.

For example:

* `Polynomial([1,2,3])` creates $p(x) = 1\,+\,2\,x \,+\,3\,x^2$
  
* `Polynomial([0,1,0,2,0,3])` creates $p(x) = x \,+\,2\,x^3\,+\,3\,x^5 $</p>
  
Can carry out arithmetic operations on polynomials, as well integrate and differentiate them.

Can also use the `polynomial` package to find a least-squares fit to data.

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Polynomials : calculating $\pi$
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

The Taylor series expansion for the trigonometric function $\arctan(y)$ is :

$$\arctan ( y) \, = \,y - \frac{y^3}{3} + \frac{y^5}{5}  - \frac{y^7}{7}  + \dots $$

Now, $\arctan(1) = \pi/4 $, so

$$ \pi = 4 \, \Big( 1- \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + ... \Big) $$

We can represent the series expansion using a numpy `Polynomial`, with coefficients:

$$0, +1, 0, -1/3, 0, +1/5, 0, -1/7,\ldots\,$$ and use it to approximate $\pi$.


<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Solution : Calculating $\pi$
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Performance
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

Python has a convenient timing function called `timeit`.

Can use this to measure the execution time of small code snippets.

To use the `timeit` function, either import module `timeit` and use `timeit.timeit` or use the magic command `%timeit`.

By default, `timeit` loops over your code 3 times and outputs the best time. It also tells you how many iterations it ran the code per loop. 
You can specify the number of loops and the number of iterations per loop.
```
%timeit -n <iterations> -r <repeats>  <code_snippet>
```

See

* `%timeit?` for more information
* https://docs.python.org/3/library/timeit.html


<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Performance (cont.)
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

Here are some `timeit` experiments for you to try. Which methods are faster?

In [58]:
# Extra : from the linear algebra package
%timeit -n 1 -r 10 np.dot(x,x)

The slowest run took 7.62 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 10: 44.9 ms per loop


<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Exercise : Darts (calculating $\pi$ again)
<hr style="border: solid 1px red; margin-bottom: -1%; ">

<br>

### A Monte Carlo method (aka "throwing darts")

Geometry gives us an expression for $\pi$: if $N_{in}$ is the
number of darts falling on the board, and $N_{tot}$ is the total
number of trials

$$
\pi \approx 4 N_{in} / N_{tot}
$$

Try using numpy arrays to compute the following:
1. Choose a sample size `ntot`
2. Generate an array of random $x$ coordinates $0 \leq x < 1$.
3. Generate an array of random $y$ coordinates $0 \leq y < 1$.
4. Count the number for which $x^2 + y^2 < 1$
5. Compute approximation to $\pi$

<br>

In [48]:
import numpy as np
import timeit

def calc_pi(ntot):
    #np.random.ranf(size) generates an array of random fp numbers
    x = np.random.ranf(ntot)
    y = np.random.ranf(ntot)
    #print(x)
    #print(y)
    
    temp = np.sqrt (x*x + y*y)
    #print (r)
    c = r [ r <= 1.0]
    #print (c)
    
    approx_pi = 4.0 * float(c.size)/float(ntot)
    
    return approx_pi

calc_pi(6)
    
    
    
    
    


3.3333333333333335

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
## Summary
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>

* Numpy introduces multi-dimensional arrays to Python


* It also provides fast numerical routines convenient for scientific computation

<br>

* Next: Matplotlib

<br>

<br>
<hr style="border: solid 1px red; margin-bottom: 2% ">
<hr style="border: solid 1px red; margin-bottom: -1%; ">
<br>